// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modulith.Modules.Products.Infrastructures.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modulith.Modules.Products.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20260215142827_CategoryFix")]
    partial class CategoryFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modulith.Modules.Products.Domain.CategoryAggregate.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 2, 15, 14, 28, 26, 868, DateTimeKind.Utc).AddTicks(5350))
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 2, 15, 14, 28, 26, 869, DateTimeKind.Utc).AddTicks(4390))
                        .HasColumnName("update_date");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("b0ad8aaa-7137-4f1e-8543-3000faaf4509"))
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f49e612-e3f9-47f3-94c0-7768e56bb0a1"),
                            CreatedDate = new DateTime(2026, 2, 15, 14, 28, 26, 872, DateTimeKind.Utc).AddTicks(2320),
                            Description = "Books featuring magical or supernatural elements often set in imaginary worlds.",
                            Name = "Fantasy",
                            Version = new Guid("10fa1bf7-75b6-4f40-ab57-52841bb0a633")
                        },
                        new
                        {
                            Id = new Guid("b594495b-eaed-4534-a8d2-205e3bde221d"),
                            CreatedDate = new DateTime(2026, 2, 15, 14, 28, 26, 872, DateTimeKind.Utc).AddTicks(3170),
                            Description = "Books exploring speculative concepts such as advanced science and technology, space exploration, or futuristic societies.",
                            Name = "Science Fiction",
                            Version = new Guid("c6935c57-651c-4edd-bf4c-59973ed43c4d")
                        },
                        new
                        {
                            Id = new Guid("5f2d7456-1639-4d66-b852-533f0ab3752d"),
                            CreatedDate = new DateTime(2026, 2, 15, 14, 28, 26, 872, DateTimeKind.Utc).AddTicks(3210),
                            Description = "Books centered around solving a crime or unraveling a puzzle, often featuring detectives or amateur sleuths.",
                            Name = "Mystery",
                            Version = new Guid("67cb5f42-9f91-459a-90f4-6ce6f59f394a")
                        },
                        new
                        {
                            Id = new Guid("97470322-75ea-4426-8556-e760aee87769"),
                            CreatedDate = new DateTime(2026, 2, 15, 14, 28, 26, 872, DateTimeKind.Utc).AddTicks(3220),
                            Description = "Books focusing on romantic relationships and emotional connections between characters.",
                            Name = "Romance",
                            Version = new Guid("e65b6790-3c0c-40f2-886d-a8028f28ecda")
                        },
                        new
                        {
                            Id = new Guid("5751fa0e-4e3c-43cf-960c-0c30ba41b5e9"),
                            CreatedDate = new DateTime(2026, 2, 15, 14, 28, 26, 872, DateTimeKind.Utc).AddTicks(3230),
                            Description = "Books set in the past, often blending fictional characters and events with real historical contexts.",
                            Name = "Historical Fiction",
                            Version = new Guid("5a91f931-23e9-43ff-ae56-cd08a2299c73")
                        },
                        new
                        {
                            Id = new Guid("567b3e58-5b63-4052-9338-64880a64c2a1"),
                            CreatedDate = new DateTime(2026, 2, 15, 14, 28, 26, 872, DateTimeKind.Utc).AddTicks(3230),
                            Description = "Books designed to provoke excitement, tension, and suspense, often involving danger and high stakes.",
                            Name = "Thriller",
                            Version = new Guid("0cfe8965-e5e3-49cf-8411-4c8f9b003b9b")
                        },
                        new
                        {
                            Id = new Guid("a7ce8d63-7abd-4964-a720-d786518473d3"),
                            CreatedDate = new DateTime(2026, 2, 15, 14, 28, 26, 872, DateTimeKind.Utc).AddTicks(3240),
                            Description = "Books intended to evoke fear, dread, or terror through supernatural or psychological elements.",
                            Name = "Horror",
                            Version = new Guid("b5bc25f5-0375-49fa-bb5e-45b16e6379d2")
                        },
                        new
                        {
                            Id = new Guid("ab5a920f-4b96-4961-939f-7dd531c6cde4"),
                            CreatedDate = new DateTime(2026, 2, 15, 14, 28, 26, 872, DateTimeKind.Utc).AddTicks(3250),
                            Description = "Books recounting the life and experiences of a real person, often written by another individual.",
                            Name = "Biography",
                            Version = new Guid("ed4f1bd5-bf46-40cb-b490-9065943ab4ec")
                        },
                        new
                        {
                            Id = new Guid("7fe4066e-18eb-446e-91ec-793c43a0eb45"),
                            CreatedDate = new DateTime(2026, 2, 15, 14, 28, 26, 872, DateTimeKind.Utc).AddTicks(3260),
                            Description = "Books offering advice, guidance, and strategies for personal growth, improvement, and self-discovery.",
                            Name = "Self-Help",
                            Version = new Guid("b8c68edf-270e-4429-98ca-31a1db8dfd28")
                        },
                        new
                        {
                            Id = new Guid("c6f265fa-98bd-4f53-bb64-d5a83e6dfa81"),
                            CreatedDate = new DateTime(2026, 2, 15, 14, 28, 26, 872, DateTimeKind.Utc).AddTicks(3260),
                            Description = "Books providing recipes, cooking techniques, and culinary inspiration for preparing various dishes and cuisines.",
                            Name = "Cooking",
                            Version = new Guid("0350a75b-9b9b-4239-a16c-939781f4a478")
                        });
                });

            modelBuilder.Entity("Modulith.Modules.Products.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 2, 15, 14, 28, 26, 873, DateTimeKind.Utc).AddTicks(1650))
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("product_code");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("quantity");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValue(new DateTime(2026, 2, 15, 14, 28, 26, 873, DateTimeKind.Utc).AddTicks(2240))
                        .HasColumnName("update_date");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("2bf0baa8-4979-4338-a60a-412fe8490033"))
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("Modulith.Modules.Products.Domain.ProductAggregate.Product", b =>
                {
                    b.HasOne("Modulith.Modules.Products.Domain.CategoryAggregate.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_products_categories_category_id");

                    b.OwnsOne("Modulith.Modules.Products.Domain.ProductAggregate.ValueObjects.ProductImage", "Image", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Alt")
                                .HasColumnType("text");

                            b1.Property<string>("ImageUrl")
                                .HasColumnType("text");

                            b1.Property<string>("Title")
                                .HasColumnType("text");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.ToJson("image");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.OwnsOne("Modulith.Modules.Products.Domain.ProductAggregate.ValueObjects.ProductPrice", "Price", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Price")
                                .HasColumnType("numeric");

                            b1.Property<decimal>("PriceSale")
                                .HasColumnType("numeric");

                            b1.HasKey("ProductId");

                            b1.ToTable("products");

                            b1.ToJson("price");

                            b1.WithOwner()
                                .HasForeignKey("ProductId")
                                .HasConstraintName("fk_products_products_id");
                        });

                    b.Navigation("Category");

                    b.Navigation("Image");

                    b.Navigation("Price");
                });

            modelBuilder.Entity("Modulith.Modules.Products.Domain.CategoryAggregate.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
